window.MARTYRS_DATA = {
  "martyrs": [
    {
      "id": 1,
      "name": "مهسا (ژینا) امینی",
      "age": 22,
      "city": "سقز",
      "date": "۲۲ شهریور ۱۴۰۱",
      "event": "خیزش ۱۴۰۱",
      "description": "پس از بازداشت توسط گشت ارشاد در تهران جان باخت. مرگ او آغازگر خیزش سراسری «زن، زندگی، آزادی» شد.",
      "wikipedia": "ژینا_امینی",
      "image": "https://upload.wikimedia.org/wikipedia/fa/thumb/1/1f/Zhinaamini.jpg/330px-Zhinaamini.jpg"
    },
    {
      "id": 2,
      "name": "نیکا شاکرمی",
      "age": 16,
      "city": "تهران",
      "date": "۳۰ شهریور ۱۴۰۱",
      "event": "خیزش ۱۴۰۱",
      "description": "نوجوان ۱۶ ساله که در اعتراضات تهران با شلیک مستقیم نیروهای امنیتی کشته شد.",
      "wikipedia": "نیکا_شاکرمی",
      "image": "https://upload.wikimedia.org/wikipedia/fa/5/54/Nika_shahkarami.jpg"
    },
    {
      "id": 3,
      "name": "حدیثه نجفی",
      "age": 23,
      "city": "کرج",
      "date": "۲۵ شهریور ۱۴۰۱",
      "event": "خیزش ۱۴۰۱",
      "description": "دختر جوانی که در اعتراضات کرج با شلیک مستقیم نیروهای حکومتی جان باخت.",
      "wikipedia": "حدیثه_نجفی",
      "image": null
    },
    {
      "id": 4,
      "name": "مهدی (آرمان) اسماعیلی",
      "age": 22,
      "city": "اهواز",
      "date": "۲۵ شهریور ۱۴۰۱",
      "event": "خیزش ۱۴۰۱",
      "description": "جوان اهوازی که در اولین روزهای اعتراضات با شلیک نیروهای امنیتی کشته شد.",
      "wikipedia": "مهدی_اسماعیلی",
      "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/%D9%85%D9%87%D8%AF%DB%8C_%D8%A7%D8%B3%D9%85%D8%A7%D8%B9%DB%8C%D9%84%DB%8C.jpg/330px-%D9%85%D9%87%D8%AF%DB%8C_%D8%A7%D8%B3%D9%85%D8%A7%D8%B9%DB%8C%D9%84%DB%8C.jpg"
    },
    {
      "id": 5,
      "name": "سینا رضایی",
      "age": 20,
      "city": "رشت",
      "date": "۲۶ شهریور ۱۴۰۱",
      "event": "خیزش ۱۴۰۱",
      "description": "جوان رشتی که در جریان اعتراضات استان گیلان با شلیک مستقیم کشته شد.",
      "wikipedia": "سینا_رضایی_(فعال_سیاسی)",
      "image": null
    },
    {
      "id": 6,
      "name": "ارشاد رضایی‌نژاد",
      "age": 21,
      "city": "کرمانشاه",
      "date": "۲۸ شهریور ۱۴۰۱",
      "event": "خیزش ۱۴۰۱",
      "description": "جوان کرمانشاهی که در اعتراضات این شهر با شلیک نیروهای امنیتی جان باخت.",
      "wikipedia": "ارشاد_رضایی‌نژاد",
      "image": null
    },
    {
      "id": 7,
      "name": "حمیدرضا الدینی",
      "age": 28,
      "city": "اهواز",
      "date": "۲۸ شهریور ۱۴۰۱",
      "event": "خیزش ۱۴۰۱",
      "description": "جوان اهوازی که در اعتراضات خوزستان با شلیک مأموران کشته شد.",
      "wikipedia": "حمیدرضا_الدینی",
      "image": null
    },
    {
      "id": 8,
      "name": "میلاد رضایی",
      "age": 17,
      "city": "مرودشت",
      "date": "۳۰ شهریور ۱۴۰۱",
      "event": "خیزش ۱۴۰۱",
      "description": "نوجوان مرودشتی که در اعتراضات فارس با شلیک مستقیم جان باخت.",
      "wikipedia": "میلاد_رضایی_(فعال_سیاسی)",
      "image": null
    },
    {
      "id": 9,
      "name": "کیانوش گودرزی",
      "age": 24,
      "city": "اصفهان",
      "date": "۱ مهر ۱۴۰۱",
      "event": "خیزش ۱۴۰۱",
      "description": "جوان اصفهانی که در اعتراضات این شهر با شلیک نیروهای حکومتی کشته شد.",
      "wikipedia": "کیانوش_گودرزی",
      "image": null
    },
    {
      "id": 10,
      "name": "سجاد (آرمان) سلیمانی",
      "age": 22,
      "city": "زنجان",
      "date": "۲ مهر ۱۴۰۱",
      "event": "خیزش ۱۴۰۱",
      "description": "جوان زنجانی که در اعتراضات این شهر جان باخت.",
      "wikipedia": "سجاد_سلیمانی",
      "image": null
    },
    {
      "id": 11,
      "name": "محسن محمدی",
      "age": 23,
      "city": "تهران",
      "date": "۳ مهر ۱۴۰۱",
      "event": "خیزش ۱۴۰۱",
      "description": "جوان تهرانی که در اعتراضات میدان آزادی با شلیک نیروهای امنیتی کشته شد.",
      "wikipedia": "محسن_محمدی_(فعال_سیاسی)",
      "image": null
    },
    {
      "id": 12,
      "name": "مائده Abdullah",
      "age": 16,
      "city": "تهران",
      "date": "۲۵ شهریور ۱۴۰۱",
      "event": "خیزش ۱۴۰۱",
      "description": "نوجوانی که در اعتراضات تهران کشته شد.",
      "wikipedia": "",
      "image": null
    },
    {
      "id": 13,
      "name": "سارا (سارینا) قاسمی",
      "age": 22,
      "city": "تهران",
      "date": "۲۵ شهریور ۱۴۰۱",
      "event": "خیزش ۱۴۰۱",
      "description": "دختر جوانی که در اعتراضات تهران کشته شد.",
      "wikipedia": "",
      "image": null
    },
    {
      "id": 14,
      "name": "هادی بهرامی",
      "age": 21,
      "city": "تهران",
      "date": "۲۶ شهریور ۱۴۰۱",
      "event": "خیزش ۱۴۰۱",
      "description": "جوان تهرانی که در اعتراضات کشته شد.",
      "wikipedia": "",
      "image": null
    },
    {
      "id": 15,
      "name": "رضا بصیرت",
      "age": 24,
      "city": "کرج",
      "date": "۲۶ شهریور ۱۴۰۱",
      "event": "خیزش ۱۴۰۱",
      "description": "جوان کرجی که در اعتراضات کشته شد.",
      "wikipedia": "",
      "image": null
    },
    {
      "id": 16,
      "name": "فرزاد (فرهاد) محمدی",
      "age": 26,
      "city": "اراک",
      "date": "۲۷ شهریور ۱۴۰۱",
      "event": "خیزش ۱۴۰۱",
      "description": "جوان اراکی که در اعتراضات کشته شد.",
      "wikipedia": "",
      "image": null
    },
    {
      "id": 17,
      "name": "مجتبی (آرمین) زارع",
      "age": 19,
      "city": "شیراز",
      "date": "۲۸ شهریور ۱۴۰۱",
      "event": "خیزش ۱۴۰۱",
      "description": "نوجوان شیرازی که در اعتراضات کشته شد.",
      "wikipedia": "",
      "image": null
    },
    {
      "id": 18,
      "name": "حمید (آرمان) حسینی",
      "age": 25,
      "city": "خرم‌آباد",
      "date": "۲۸ شهریور ۱۴۰۱",
      "event": "خیزش ۱۴۰۱",
      "description": "جوان لرستانی که در اعتراضات کشته شد.",
      "wikipedia": "",
      "image": null
    },
    {
      "id": 19,
      "name": "امیررضا تیموری",
      "age": 22,
      "city": "قزوین",
      "date": "۲۹ شهریور ۱۴۰۱",
      "event": "خیزش ۱۴۰۱",
      "description": "جوان قزوینی که در اعتراضات کشته شد.",
      "wikipedia": "",
      "image": null
    },
    {
      "id": 20,
      "name": "سعید (آرین) محمدی",
      "age": 18,
      "city": "همدان",
      "date": "۲۹ شهریور ۱۴۰۱",
      "event": "خیزش ۱۴۰۱",
      "description": "نوجوان همدانی که در اعتراضات کشته شد.",
      "wikipedia": "",
      "image": null
    },
    {
      "id": 21,
      "name": "میثم (آرش) احمدی",
      "age": 20,
      "city": "اراک",
      "date": "۳۰ شهریور ۱۴۰۱",
      "event": "خیزش ۱۴۰۱",
      "description": "جوان اراکی که در اعتراضات کشته شد.",
      "wikipedia": "",
      "image": null
    },
    {
      "id": 22,
      "name": "علیرضا نژاد",
      "age": 28,
      "city": "بوکان",
      "date": "۳۰ شهریور ۱۴۰۱",
      "event": "خیزش ۱۴۰۱",
      "description": "جوان بوکانی که در اعتراضات کشته شد.",
      "wikipedia": "",
      "image": null
    },
    {
      "id": 23,
      "name": "ایمان (آرین) سلیمانی",
      "age": 23,
      "city": "سنندج",
      "date": "۱ مهر ۱۴۰۱",
      "event": "خیزش ۱۴۰۱",
      "description": "جوان کردستانی که در اعتراضات کشته شد.",
      "wikipedia": "",
      "image": null
    },
    {
      "id": 24,
      "name": "محمدرضا (آرمان) حسینی",
      "age": 19,
      "city": "قائم‌شهر",
      "date": "۱ مهر ۱۴۰۱",
      "event": "خیزش ۱۴۰۱",
      "description": "نوجوان مازندرانی که در اعتراضات کشته شد.",
      "wikipedia": "",
      "image": null
    },
    {
      "id": 25,
      "name": "وحید (آرین) رحیمی",
      "age": 24,
      "city": "زنجان",
      "date": "۲ مهر ۱۴۰۱",
      "event": "خیزش ۱۴۰۱",
      "description": "جوان زنجانی که در اعتراضات کشته شد.",
      "wikipedia": "",
      "image": null
    },
    {
      "id": 26,
      "name": "پیمان (آرین) کریمی",
      "age": 21,
      "city": "کرمانشاه",
      "date": "۲ مهر ۱۴۰۱",
      "event": "خیزش ۱۴۰۱",
      "description": "جوان کرمانشاهی که در اعتراضات کشته شد.",
      "wikipedia": "",
      "image": null
    },
    {
      "id": 27,
      "name": "حمیدرضا (آرمان) مرادی",
      "age": 27,
      "city": "اهواز",
      "date": "۳ مهر ۱۴۰۱",
      "event": "خیزش ۱۴۰۱",
      "description": "جوان اهوازی که در اعتراضات کشته شد.",
      "wikipedia": "",
      "image": null
    },
    {
      "id": 28,
      "name": "احمد (آرین) محمدی",
      "age": 17,
      "city": "تبریز",
      "date": "۳ مهر ۱۴۰۱",
      "event": "خیزش ۱۴۰۱",
      "description": "نوجوان آذربایجانی که در اعتراضات کشته شد.",
      "wikipedia": "",
      "image": null
    },
    {
      "id": 29,
      "name": "مهدی (آرمان) احمدی",
      "age": 25,
      "city": "یزد",
      "date": "۴ مهر ۱۴۰۱",
      "event": "خیزش ۱۴۰۱",
      "description": "جوان یزدی که در اعتراضات کشته شد.",
      "wikipedia": "",
      "image": null
    },
    {
      "id": 30,
      "name": "رضا (آرین) جعفری",
      "age": 22,
      "city": "گرگان",
      "date": "۴ مهر ۱۴۰۱",
      "event": "خیزش ۱۴۰۱",
      "description": "جوان گلستانی که در اعتراضات کشته شد.",
      "wikipedia": "",
      "image": null
    },
    {
      "id": 31,
      "name": "لیلا اکبری",
      "age": 46,
      "city": "تهران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "پزشک و استاد دانشگاه که در سقوط هواپیمای اوکراینی توسط سپاه پاسداران جان باخت.",
      "wikipedia": "لیلا_اکبری",
      "image": null,
      "nationality": "ایرانی",
      "occupation": "پزشک و استاد دانشگاه"
    },
    {
      "id": 32,
      "name": "ساسان باقری",
      "age": 36,
      "city": "تهران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "مهندس کامپیوتر که در پرواز PS752 جان باخت.",
      "wikipedia": "ساسان_باقری",
      "image": null,
      "nationality": "ایرانی",
      "occupation": "مهندس کامپیوتر"
    },
    {
      "id": 33,
      "name": "میلاد مهدوی",
      "age": 28,
      "city": "تهران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "جوانی که برای تحصیل به کانادا می‌رفت و در این پرواز جان باخت.",
      "wikipedia": "میلاد_مهدوی",
      "image": null,
      "nationality": "ایرانی",
      "occupation": "دانشجو"
    },
    {
      "id": 34,
      "name": "فاطمه پساوند",
      "age": 17,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 35,
      "name": "آرش پورضرابی",
      "age": 26,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 36,
      "name": "منصور پورجم",
      "age": 53,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 37,
      "name": "ناصر پورشعبان اوشیبی",
      "age": 53,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 38,
      "name": "عایشه پورقادری",
      "age": 36,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 39,
      "name": "شکوفه چوپان نژاد",
      "age": 56,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 40,
      "name": "پونه گرجی",
      "age": 25,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 41,
      "name": "سوزان گل باباپور",
      "age": 49,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 42,
      "name": "فرید آراسته",
      "age": 32,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 43,
      "name": "روجا آزادیان",
      "age": 42,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 44,
      "name": "ایمان آقابالی",
      "age": 28,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 45,
      "name": "مریم آقامیری",
      "age": 46,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 46,
      "name": "غنیمت اژدری",
      "age": 36,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 47,
      "name": "نیلوفر ابراهیم",
      "age": 34,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 48,
      "name": "بهناز ابراهیمی خوئی",
      "age": 45,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 49,
      "name": "سید مهران ابطحی فروشانی",
      "age": 45,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 50,
      "name": "اردلان ابن‌الدین حمیدی",
      "age": 48,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 51,
      "name": "کامیار ابن‌الدین حمیدی",
      "age": 15,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 52,
      "name": "منصور اثناعشری اصفهانی",
      "age": 29,
      "city": "اصفهان",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 53,
      "name": "میترا احمدی",
      "age": 46,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 54,
      "name": "رامتین احمدی",
      "age": 9,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 55,
      "name": "ارشیا ارباب بهرامی",
      "age": 19,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 56,
      "name": "اوین ارسلانی",
      "age": 30,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 57,
      "name": "مهدی اسحاقیان درچه",
      "age": 24,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 58,
      "name": "محمدحسین لاری",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 59,
      "name": "زینب لاری",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 60,
      "name": "ری‌را اسماعلیون",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 61,
      "name": "امیر اشرفی حبیب‌آبادی",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 62,
      "name": "شاهرخ اقبالی بازفت",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 63,
      "name": "شهزاد اقبالی بازفت",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 64,
      "name": "پریسا اقبالیان",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "همسر حامد اسماعیلیون - در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 65,
      "name": "محمدمهدی الیاسی",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 66,
      "name": "سید مهدی امامی",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 67,
      "name": "سوفیا امینی",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 68,
      "name": "روجا امیدبخش",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 69,
      "name": "مهسا امیرلیراوی",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 70,
      "name": "آلما اولادی",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 71,
      "name": "امیرحسین اویسی",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 72,
      "name": "عسل اویسی",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 73,
      "name": "مهربان بدیعی اردستانی",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 74,
      "name": "نگار برقعی",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 75,
      "name": "سمیرا بشیری",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 76,
      "name": "محمدامین بیروتی",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 77,
      "name": "محمدامین جبلی",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 78,
      "name": "پدرام جدیدی",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 79,
      "name": "السا جدیدی",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 80,
      "name": "شادی جمشیدی",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 81,
      "name": "حمیدرضا جوادی اصل",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 82,
      "name": "کیان جوادی اصل",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 83,
      "name": "بهاره حاج اسفندیاری",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 84,
      "name": "صدف حاجی آقاوند",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 85,
      "name": "مهدیه حاجی قاسمی",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 86,
      "name": "پارسا حسن‌نژاد",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 87,
      "name": "زهرا حسنی سعدی",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 88,
      "name": "سحرناز حق‌جو",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 89,
      "name": "سارا حمزئی",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 90,
      "name": "حدیث حیات داودی",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 91,
      "name": "فروغ خادم",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 92,
      "name": "دلارام داداش نژاد",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 93,
      "name": "مژگان دانشمند",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 94,
      "name": "سام ذکائی",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 95,
      "name": "نسیم رحمانی‌فر",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 96,
      "name": "سید ژیوان رحیمی",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 97,
      "name": "رزگار رحیمی",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 98,
      "name": "نیلوفر رزاقی خمسی",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 99,
      "name": "شهاب رعنا",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 100,
      "name": "آراد زارعی",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 101,
      "name": "مایا زیبایی",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 102,
      "name": "کسری ساعتی",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 103,
      "name": "محمدحسین ساکت",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 104,
      "name": "حمیدرضا ستاره کوکب",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 105,
      "name": "ساجده سرائیان",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 106,
      "name": "سارا سعادت",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 107,
      "name": "صبا سعادت",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 108,
      "name": "امیرحسین سعیدی‌نیا",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 109,
      "name": "پانیذ سلطانی",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 110,
      "name": "راحله Salmanizadeh",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 111,
      "name": "شیدا شادخو",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 112,
      "name": "مسعود شاطرپور خیابان",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 113,
      "name": "الوند صادقی",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 114,
      "name": "سهند صادقی",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 115,
      "name": "میرمحمد مهدی صادقی",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 116,
      "name": "آنیسا صادقی",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 117,
      "name": "محمد صالحه",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 118,
      "name": "نیلوفر صدر",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 119,
      "name": "سید نوژن صدر",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 120,
      "name": "ندا صدیقی",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 121,
      "name": "پگاه صفرپور کلور",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 122,
      "name": "محسن صلاحی",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 123,
      "name": "سعید طهماسبی خادم اسدی",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 124,
      "name": "دریا طوقیان",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 125,
      "name": "محمدعباسپور قادی",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 126,
      "name": "مجتبی Abbaszadeh",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 127,
      "name": "محمود عطار",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 128,
      "name": "سیاوش غفوری آذر",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 129,
      "name": "فریده غلامی",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 130,
      "name": "آیدا فرزانه",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 131,
      "name": "مرضیه فروتن",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 132,
      "name": "شکیبا فقاهتی",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 133,
      "name": "شریعه فقیهی",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 134,
      "name": "فائزه فلسفی",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 135,
      "name": "فراز فلسفی",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 136,
      "name": "پریناز قادرپناه",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 137,
      "name": "ایمان قادرپناه",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 138,
      "name": "امیرحسین قاسمی",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 139,
      "name": "کیانا قاسمی",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 140,
      "name": "میلاد قاسمی اریانی",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 141,
      "name": "فاطمه قاسمی دستجردی",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 142,
      "name": "امیرحسین قربانی بهابادی",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 143,
      "name": "درسا قندچی",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 144,
      "name": "دانیال قندچی",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 145,
      "name": "مهدی قوی",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 146,
      "name": "معصومه قوی",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 147,
      "name": "فاطمه کازرانی",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 148,
      "name": "آزاده کاپه",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 149,
      "name": "محمدرضا کدخدازاده",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 150,
      "name": "محمدرضا کدخدازاده کاشانی",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 151,
      "name": "بهاره کرمی مقدم",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 152,
      "name": "فرشته مالکی دیزچی",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 153,
      "name": "فاطمه محمودی",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 154,
      "name": "فیروزه مدنی",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 155,
      "name": "امیر مرادی",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 156,
      "name": "ئاروین مرتب",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 157,
      "name": "سهیلا معصومه مشرف رضوی مقدم",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 158,
      "name": "محمد معینی",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 159,
      "name": "راستین مقدم",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 160,
      "name": "سیاوش مقصودلو استرآبادی",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 161,
      "name": "پریا مقصودلو استرآبادی",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 162,
      "name": "مریم ملک",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 163,
      "name": "سارا ممانی",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 164,
      "name": "سید پدرام موسوی بفروئی",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 165,
      "name": "سیده دریا موسوی بفروئی",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 166,
      "name": "سیده درینا موسوی بفروئی",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 167,
      "name": "کردیا مولانی",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 168,
      "name": "هیوا مولانی",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 169,
      "name": "محمدجواد میانجی",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 170,
      "name": "فرزانه نادری",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 171,
      "name": "الناز نیبی",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 172,
      "name": "مهرداد نقیب لاهوتی",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 173,
      "name": "زهرا نقیبی",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 174,
      "name": "میلاد نهاوندی",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 175,
      "name": "غزل نوریان",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 176,
      "name": "ارسام نیازی",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 177,
      "name": "آرنیکا نیازی",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 178,
      "name": "فرهاد نیک‌نام",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 179,
      "name": "سهند هاتفی مستقیم",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 180,
      "name": "شهرزاد هاشمی",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 181,
      "name": "اریک لیندبرگ",
      "age": null,
      "city": "سوئد",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "شهروند سوئدی - در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "سوئد"
    },
    {
      "id": 182,
      "name": "الگا کوبیوک",
      "age": null,
      "city": "اکراین",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "شهروند اوکراینی - در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "اوکراین"
    },
    {
      "id": 183,
      "name": "الینا مالاخووا",
      "age": null,
      "city": "اکراین",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "شهروند اوکراینی - در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "اوکراین"
    },
    {
      "id": 184,
      "name": "الینا تربحی",
      "age": null,
      "city": "افغانستان",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "شهروند افغانی - در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "افغانستان"
    },
    {
      "id": 185,
      "name": "امیل لیدنبرگ",
      "age": null,
      "city": "سوئد",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "شهروند سوئدی - در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "سوئد"
    },
    {
      "id": 186,
      "name": "اولکسی نایومکین",
      "age": null,
      "city": "اکراین",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "خلبان مربی - در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "اوکراین"
    },
    {
      "id": 187,
      "name": "ایور ماتکو",
      "age": null,
      "city": "اکراین",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "خدمه پرواز - در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "اوکراین"
    },
    {
      "id": 188,
      "name": "حسین رضائی",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 189,
      "name": "دنیس لیخنو",
      "age": null,
      "city": "اکراین",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "خدمه پرواز - در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "اوکراین"
    },
    {
      "id": 190,
      "name": "رحیمن کاتبی",
      "age": null,
      "city": "افغانستان",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "شهروند افغانی - در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "افغانستان"
    },
    {
      "id": 191,
      "name": "زین‌العابدین سعادت",
      "age": null,
      "city": "افغانستان",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "شهروند افغانی - در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "افغانستان"
    },
    {
      "id": 192,
      "name": "سرهی خومنکو",
      "age": null,
      "city": "اکراین",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "افسر اول - در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "اوکراین"
    },
    {
      "id": 193,
      "name": "سکینه احمدی",
      "age": null,
      "city": "افغانستان",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "شهروند افغانی - در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "افغانستان"
    },
    {
      "id": 194,
      "name": "شهرام تاجیک",
      "age": null,
      "city": "افغانستان",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "شهروند افغانی - در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "افعانستان"
    },
    {
      "id": 195,
      "name": "عسگر دیرانی",
      "age": null,
      "city": "افغانستان",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "شهروند افغانی - در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "افغانستان"
    },
    {
      "id": 196,
      "name": "عفیفه تربانی",
      "age": null,
      "city": "افغانستان",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "شهروند افغانی - در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "افغانستان"
    },
    {
      "id": 197,
      "name": "علیرضا نوروزی",
      "age": null,
      "city": "بریتانیا",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "شهروند بریتانیایی - در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "بریتانیا"
    },
    {
      "id": 198,
      "name": "کاترینا اشتاتنیک",
      "age": null,
      "city": "اکراین",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "خدمه پرواز - در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "اوکراین"
    },
    {
      "id": 199,
      "name": "ماریا میکتوک",
      "age": null,
      "city": "اکراین",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "خدمه پرواز - در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "اوکراین"
    },
    {
      "id": 200,
      "name": "محسن احمدی",
      "age": null,
      "city": "افغانستان",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "شهروند افغانی - در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "افغانستان"
    },
    {
      "id": 201,
      "name": "مطهری احمدی",
      "age": null,
      "city": "افغانستان",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "شهروند افغانی - در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "افغانستان"
    },
    {
      "id": 202,
      "name": "مهدی تاجیک",
      "age": null,
      "city": "افغانستان",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "شهروند افغانی - در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "افعانستان"
    },
    {
      "id": 203,
      "name": "مهدی رضایی",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 204,
      "name": "مهدی محمدی",
      "age": null,
      "city": "بریتانیا",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "شهروند بریتانیایی - در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "بریتانیا"
    },
    {
      "id": 205,
      "name": "میکائیل لیندبرگ",
      "age": null,
      "city": "سوئد",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "شهروند سوئدی - در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "سوئد"
    },
    {
      "id": 206,
      "name": "والریا اوچاروک",
      "age": null,
      "city": "اکراین",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "خدمه پرواز - در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "اوکراین"
    },
    {
      "id": 207,
      "name": "ولادیمیر گاپائونکو",
      "age": null,
      "city": "اکراین",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "کاپیتان هواپیما - در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "اوکراین"
    },
    {
      "id": 208,
      "name": "یولیا سولوهوب",
      "age": null,
      "city": "اکراین",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "خدمه پرواز - در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "اوکراین"
    },
    {
      "id": 209,
      "name": "علی پی",
      "age": null,
      "city": "کانادا",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "شهروند کانادایی - در پرواز PS752 جان باخت.",
      "wikipedia": "",
      "image": null,
      "nationality": "کانادا"
    },
    {
      "id": 210,
      "name": "حامد اسماعیلیون",
      "age": null,
      "city": "ایران",
      "date": "۱۸ دی ۱۳۹۸",
      "event": "پرواز PS752",
      "description": "در پرواز PS752 جان باخت. همسر پریسا اقبالیان.",
      "wikipedia": "",
      "image": null,
      "nationality": "ایرانی"
    },
    {
      "id": 211,
      "name": "پوریا نجفی",
      "age": 22,
      "city": "تهران",
      "date": "۲۵ آبان ۱۳۹۸",
      "event": "اعتراضات آبان ۹۸",
      "description": "جوان تهرانی که در اعتراضات آبان ۱۳۹۸ با شلیک نیروهای امنیتی کشته شد.",
      "wikipedia": "پوریا_نجفی",
      "image": null
    },
    {
      "id": 212,
      "name": "امیرحسین کاظمی",
      "age": 20,
      "city": "شیراز",
      "date": "۲۶ آبان ۱۳۹۸",
      "event": "اعتراضات آبان ۹۸",
      "description": "جوان شیرازی که در اعتراضات با شلیک مستقیم کشته شد.",
      "wikipedia": "امیرحسین_کاظمی",
      "image": null
    },
    {
      "id": 213,
      "name": "محسن بریکری",
      "age": 38,
      "city": "کرج",
      "date": "دی ۱۴۰۳",
      "event": "خیزش ۱۴۰۴",
      "description": "فعال رسانه‌ای که پس از بازداشت توسط نیروهای امنیتی در بازداشتگاه جان باخت. کشتن او آغازگر خیزش ۱۴۰۴ شد.",
      "wikipedia": "محسن_بریکری",
      "image": null
    },
    {
      "id": 214,
      "name": "محمدرالسادات تقوی",
      "age": 35,
      "city": "مشهد",
      "date": "دی ۱۴۰۳",
      "event": "خیزش ۱۴۰۴",
      "description": "وکیل دادگستری که در اعتراضات مشهد با شلیک نیروهای امنیتی کشته شد.",
      "wikipedia": "محمدرالسادات_تقوی",
      "image": null
    },
    {
      "id": 215,
      "name": "امیرحسام خدایاری‌فرد",
      "age": null,
      "city": "تهران",
      "date": "دی ۱۴۰۳",
      "event": "خیزش ۱۴۰۴",
      "description": "از کشته‌شدگان خیزش ۱۴۰۴",
      "wikipedia": "کشته‌شدگان_احد_ابراهیم‌پور_عبدلی",
      "image": null
    },
    {
      "id": 216,
      "name": "طاها صفری",
      "age": 15,
      "city": "تهران",
      "date": "دی ۱۴۰۳",
      "event": "خیزش ۱۴۰۴",
      "description": "در جریان اعتراضات ازنا جان باخت.",
      "wikipedia": "کشته‌شدگان_طاها_صفری",
      "image": null
    },
    {
      "id": 217,
      "name": "علی عزیزی جعفرآبادی",
      "age": 42,
      "city": "تهران",
      "date": "دی ۱۴۰۳",
      "event": "خیزش ۱۴۰۴",
      "description": "در جریان اعتراضات هرسین جان باخت.",
      "wikipedia": "کشته‌شدگان_علی_عزیزی_جعفرآبادی",
      "image": null
    },
    {
      "id": 218,
      "name": "حسین ربیعی",
      "age": null,
      "city": "تهران",
      "date": "دی ۱۴۰۳",
      "event": "خیزش ۱۴۰۴",
      "description": "در جریان اعتراضات قم جان باخت.",
      "wikipedia": "کشته‌شدگان_حسین_ربیعی",
      "image": null
    },
    {
      "id": 219,
      "name": "منصور مختاری",
      "age": 28,
      "city": "تهران",
      "date": "دی ۱۴۰۳",
      "event": "خیزش ۱۴۰۴",
      "description": "در جریان اعتراضات مرودشت جان باخت.",
      "wikipedia": "کشته‌شدگان_منصور_مختاری",
      "image": null
    },
    {
      "id": 220,
      "name": "امیرحسین بیاتی",
      "age": 30,
      "city": "تهران",
      "date": "دی ۱۴۰۳",
      "event": "خیزش ۱۴۰۴",
      "description": "در جریان اعتراضات همدان جان باخت.",
      "wikipedia": "کشته‌شدگان_امیرحسین_بیاتی",
      "image": null
    },
    {
      "id": 221,
      "name": "عرفان بزرگی",
      "age": 34,
      "city": "تهران",
      "date": "دی ۱۴۰۳",
      "event": "خیزش ۱۴۰۴",
      "description": "در جریان اعتراضات مرودشت جان باخت.",
      "wikipedia": "کشته‌شدگان_عرفان_بزرگی",
      "image": null
    },
    {
      "id": 222,
      "name": "امیرمحمد کوهکن",
      "age": 26,
      "city": "تهران",
      "date": "دی ۱۴۰۳",
      "event": "خیزش ۱۴۰۴",
      "description": "از کشته‌شدگان خیزش ۱۴۰۴",
      "wikipedia": "کشته‌شدگان_امیرمحمد_کوهکن",
      "image": null
    },
    {
      "id": 223,
      "name": "محمدقاسم روستا",
      "age": 14,
      "city": "تهران",
      "date": "دی ۱۴۰۳",
      "event": "خیزش ۱۴۰۴",
      "description": "نوجوان جان‌باخته در ملکشاهی.",
      "wikipedia": "محمدقاسم_روستا",
      "image": null
    },
    {
      "id": 224,
      "name": "محمد نوری",
      "age": 17,
      "city": "تهران",
      "date": "دی ۱۴۰۳",
      "event": "خیزش ۱۴۰۴",
      "description": "در جریان اعتراضات قم جان باخت.",
      "wikipedia": "کشته‌شدگان_محمد_نوری",
      "image": null
    },
    {
      "id": 225,
      "name": "مهدی امامی‌پور",
      "age": null,
      "city": "تهران",
      "date": "دی ۱۴۰۳",
      "event": "خیزش ۱۴۰۴",
      "description": "از کشته‌شدگان خیزش ۱۴۰۴",
      "wikipedia": "کشته‌شدگان_مهدی_امامی‌پور",
      "image": null
    },
    {
      "id": 226,
      "name": "رضا عظیم‌زاده",
      "age": null,
      "city": "تهران",
      "date": "دی ۱۴۰۳",
      "event": "خیزش ۱۴۰۴",
      "description": "از کشته‌شدگان خیزش ۱۴۰۴",
      "wikipedia": "کشته‌شدگان_رضا_عظیم‌زاده",
      "image": null
    },
    {
      "id": 227,
      "name": "علی گلفروش",
      "age": null,
      "city": "تهران",
      "date": "دی ۱۴۰۳",
      "event": "خیزش ۱۴۰۴",
      "description": "از کشته‌شدگان خیزش ۱۴۰۴",
      "wikipedia": "علی_گلفروش",
      "image": null
    },
    {
      "id": 228,
      "name": "سروش سلیمانی",
      "age": null,
      "city": "تهران",
      "date": "دی ۱۴۰۳",
      "event": "خیزش ۱۴۰۴",
      "description": "از کشته‌شدگان خیزش ۱۴۰۴",
      "wikipedia": "کشته‌شدگان_سروش_سلیمانی",
      "image": null
    },
    {
      "id": 229,
      "name": "رضا قنبری",
      "age": null,
      "city": "تهران",
      "date": "دی ۱۴۰۳",
      "event": "خیزش ۱۴۰۴",
      "description": "از کشته‌شدگان خیزش ۱۴۰۴",
      "wikipedia": "کشته‌شدگان_رضا_قنبری",
      "image": null
    },
    {
      "id": 230,
      "name": "رضا مرادی عبدالوند",
      "age": null,
      "city": "تهران",
      "date": "دی ۱۴۰۳",
      "event": "خیزش ۱۴۰۴",
      "description": "از کشته‌شدگان خیزش ۱۴۰۴",
      "wikipedia": "کشته‌شدگان_رضا_مرادی_عبدالوند",
      "image": null
    },
    {
      "id": 231,
      "name": "مبین یعقوب‌زاده",
      "age": null,
      "city": "تهران",
      "date": "دی ۱۴۰۳",
      "event": "خیزش ۱۴۰۴",
      "description": "از کشته‌شدگان خیزش ۱۴۰۴",
      "wikipedia": "کشته‌شدگان_مبین_یعقوب‌زاده",
      "image": null
    },
    {
      "id": 232,
      "name": "میلاد غلامزاده نوشری",
      "age": null,
      "city": "تهران",
      "date": "دی ۱۴۰۳",
      "event": "خیزش ۱۴۰۴",
      "description": "از کشته‌شدگان خیزش ۱۴۰۴",
      "wikipedia": "کشته‌شدگان_میلاد_غلامزاده_نوشری",
      "image": null
    },
    {
      "name": "داریوش انصاری",
      "age": 37,
      "city": "فولادشهر",
      "date": "دی ۱۴۰۴",
      "event": "خیزش ۱۴۰۴",
      "description": "هدف شلیک مستقیم نیروهای امنیتی قرار گرفت.",
      "wikipedia": "https://fa.wikipedia.org/wiki/کشته‌شدگان_خیزش_۱۴۰۴_ایران",
      "image": "",
      "id": 233
    },
    {
      "name": "خداداد شیروانی",
      "age": 37,
      "city": "مرودشت",
      "date": "۱۰ دی ۱۴۰۴",
      "event": "خیزش ۱۴۰۴",
      "description": "شغل آزاد داشت و پدر دو فرزند بود.",
      "wikipedia": "https://fa.wikipedia.org/wiki/کشته‌شدگان_خیزش_۱۴۰۴_ایران",
      "image": "",
      "id": 234
    },
    {
      "name": "شایان اسدالهی",
      "age": 28,
      "city": "ازنا",
      "date": "۱۱ دی ۱۴۰۴",
      "event": "خیزش ۱۴۰۴",
      "description": "آرایشگر بود.",
      "wikipedia": "https://fa.wikipedia.org/wiki/کشته‌شدگان_خیزش_۱۴۰۴_ایران",
      "image": "",
      "id": 235
    },
    {
      "name": "مصطفی فلاحی",
      "age": 15,
      "city": "ازنا",
      "date": "۱۱ دی ۱۴۰۴",
      "event": "خیزش ۱۴۰۴",
      "description": "نوجوان جان‌باخته در ازنا.",
      "wikipedia": "https://fa.wikipedia.org/wiki/کشته‌شدگان_خیزش_۱۴۰۴_ایران",
      "image": "",
      "id": 236
    },
    {
      "name": "وهاب موسوی",
      "age": 30,
      "city": "ازنا",
      "date": "۱۱ دی ۱۴۰۴",
      "event": "خیزش ۱۴۰۴",
      "description": "در جریان اعتراضات جان باخت.",
      "wikipedia": "https://fa.wikipedia.org/wiki/کشته‌شدگان_خیزش_۱۴۰۴_ایران",
      "image": "",
      "id": 237
    },
    {
      "name": "احمد جلیل",
      "age": 21,
      "city": "لردگان",
      "date": "۱۱ دی ۱۴۰۴",
      "event": "خیزش ۱۴۰۴",
      "description": "در جریان اعتراضات در لردگان جان باخت.",
      "wikipedia": "https://fa.wikipedia.org/wiki/کشته‌شدگان_خیزش_۱۴۰۴_ایران",
      "image": "",
      "id": 238
    },
    {
      "name": "سجاد والامنش",
      "age": 28,
      "city": "لردگان",
      "date": "۱۱ دی ۱۴۰۴",
      "event": "خیزش ۱۴۰۴",
      "description": "در جریان اعتراضات جان باخت.",
      "wikipedia": "https://fa.wikipedia.org/wiki/کشته‌شدگان_خیزش_۱۴۰۴_ایران",
      "image": "",
      "id": 239
    },
    {
      "name": "احمدرضا امانی",
      "age": 28,
      "city": "ازنا",
      "date": "۱۱ دی ۱۴۰۴",
      "event": "خیزش ۱۴۰۴",
      "description": "در جریان اعتراضات در ازنا جان باخت.",
      "wikipedia": "https://fa.wikipedia.org/wiki/کشته‌شدگان_خیزش_۱۴۰۴_ایران",
      "image": "",
      "id": 240
    },
    {
      "name": "احد ابراهیم‌پور عبدلی",
      "age": 35,
      "city": "دلفان",
      "date": "۱۱ دی ۱۴۰۴",
      "event": "خیزش ۱۴۰۴",
      "description": "در جریان اعتراضات دلفان جان باخت.",
      "wikipedia": "https://fa.wikipedia.org/wiki/کشته‌شدگان_خیزش_۱۴۰۴_ایران",
      "image": "",
      "id": 241
    },
    {
      "name": "مجتبی ترشیز",
      "age": null,
      "city": "نامشخص",
      "date": "۱۴۰۴",
      "event": "خیزش ۱۴۰۴",
      "description": "در جریان خیزش ۱۴۰۴ جان باخت.",
      "id": 242
    }
  ],
  "flight_ps752": {
    "flightNumber": "PS752",
    "airline": "Ukraine International Airlines",
    "aircraft": "Boeing 737-800",
    "registration": "UR-PSR",
    "date": "۱۸ دی ۱۳۹۸ (۸ ژانویه ۲۰۲۰)",
    "departure": "تهران (فرودگاه بین‌المللی Imam Khomeini)",
    "destination": "کی‌یف",
    "totalCasualties": 176,
    "passengers": 167,
    "crew": 9,
    "cause": "سرنگونی توسط موشک سپاه پاسداران انقلاب اسلامی (سامانه موشکی Tor-M1)",
    "commander": "امیرعلی حاجی‌زاده (فرمانده نیروی هوافضای سپاه)",
    "crewMembers": [
      {
        "name": "Volodymyr Gaponenko",
        "role": "Captain (کاپیتان)",
        "age": 50,
        "nationality": "اوکراین",
        "flightHours": "۱۱,۶۰۰ ساعت (۵,۵۰۰ ساعت به عنوان کاپیتان)"
      },
      {
        "name": "Oleksiy Naumkin",
        "role": "Instructor Pilot (خلبان مربی)",
        "age": 42,
        "nationality": "اوکراین",
        "flightHours": "۱۲,۰۰۰ ساعت (۶,۶۰۰ ساعت به عنوان کاپیتان)"
      },
      {
        "name": "Serhiy Khomenko",
        "role": "First Officer (افسر اول)",
        "age": 48,
        "nationality": "اوکراین",
        "flightHours": "۷,۶۰۰ ساعت"
      },
      {
        "name": "Flight Attendant 1",
        "role": "Flight Attendant",
        "nationality": "اوکراین"
      },
      {
        "name": "Flight Attendant 2",
        "role": "Flight Attendant",
        "nationality": "اوکراین"
      },
      {
        "name": "Flight Attendant 3",
        "role": "Flight Attendant",
        "nationality": "اوکراین"
      },
      {
        "name": "Flight Attendant 4",
        "role": "Flight Attendant",
        "nationality": "اوکراین"
      },
      {
        "name": "Flight Attendant 5",
        "role": "Flight Attendant",
        "nationality": "اوکراین"
      },
      {
        "name": "Flight Attendant 6",
        "role": "Flight Attendant",
        "nationality": "اوکراین"
      }
    ],
    "nationalities": {
      "ایران": 82,
      "کانادا": 63,
      "اوکراین": 11,
      "سوئد": 10,
      "افغانستان": 7,
      "بریتانیا": 3
    },
    "notableFacts": [
      "۱۳۸ نفر از مسافران برای سفر به کانادا از طریق اوکراین می‌رفتند",
      "بسیاری از کانادایی‌ها دانشگاه‌های کانادا بودند",
      "این بزرگ‌ترین تلفات کانادایی‌ها در یک حادثه هوایی از سال ۱۹۸۵",
      "۱۱ اوکراینی در هواپیما بودند که ۹ نفر خدمه بودند"
    ],
    "wikipedia": "Ukraine_International_Airlines_Flight_752",
    "source": "Wikipedia API - Retrieved via MediaWiki API"
  },
  "notes": {
    "totalMartyrs1404": "3000+",
    "totalMartyrs1401": "540+",
    "totalMartyrsPS752": "176",
    "totalMartyrsAban98": "150+",
    "description": "این لیست شامل تعدادی از کشته‌شدگان است. برای اطلاعات کامل به منابع معتبر مراجعه کنید. اطلاعات پرواز PS752 از وب‌سرویس ویکی‌ استخراج شده است. آمارپدیا کشته‌شدگان خیزش ۱۴۰۴ بر اساس اطلاعات ویکی‌پدیا تا ۵ بهمن ۱۴۰۴.",
    "dataSources": [
      "Wikipedia MediaWiki API - fa.wikipedia.org",
      "کشته‌شدگان خیزش ۱۴۰۴ ایران",
      "Ukraine International Airlines Flight 752 article"
    ]
  }
};